name: avahi-client
version: '0.0'
version-script: dpkg-deb -f parts/avahi-utils/ubuntu/download/avahi-utils_*.deb Version | cut -c -6
summary: Avahi sample client
description: |
    Avahi sample client

grade: stable
confinement: strict

plugs:
  avahi-daemon-socket:
    interface: content
    content: avahi-daemon-socket
    default-provider: avahi:daemon-socket
    target: $SNAP_DATA/var/run/avahi-daemon

layout:
    /etc/nsswitch.conf:
        bind-file: $SNAP_COMMON/etc/nsswitch.conf

apps:
    browse:
        command: avahi-browse
        plugs:
          - avahi-observe

    browse-domains:
        command: avahi-browse-domains
        plugs:
          - avahi-observe

    publish-address:
        command: avahi-publish-address
        plugs:
          - avahi-control

    publish-service:
        command: avahi-publish-service
        plugs:
          - avahi-control

    resolve-address:
        command: avahi-resolve-address
        plugs:
          - avahi-observe

    resolve-host-name:
        command: avahi-resolve-host-name
        plugs:
          - avahi-observe

    publish:
        command: avahi-publish
        plugs:
          - avahi-control

    resolve:
        command: avahi-resolve
        plugs:
          - avahi-observe

    set-host-name:
        command: avahi-set-host-name
        plugs:
          - avahi-control
    ping:
        command: ping
        plugs:
          - avahi-control
          - network-observe

    ping6:
        command: ping6
        plugs:
          - avahi-control
          - network-observe

parts:
  avahi-utils:
    plugin: nil
    stage-packages: [avahi-utils]
    stage:
      - -var
      - -etc
      - -lib
      - -usr/bin/d*
      - -usr/bin/host
      - -usr/sbin
      - -usr/share
      - -usr/lib/avahi
      - -usr/lib/dbus-1.0
      - -usr/lib/gcc
      - -usr/lib/tmpfiles.d
    build-packages: [iputils-ping]
    install: |
      find ${SNAPCRAFT_PART_INSTALL}/usr/lib/*linux-gnu*/* ! -name "libavahi*" -exec rm -rf {} +
      find ${SNAPCRAFT_PART_INSTALL}/usr/lib/*linux-gnu*/* -name "libavahi-core*" -exec rm -f {} \;

  nss-mdns:
    plugin: autotools
    source: https://github.com/lathiat/nss-mdns.git
    configflags:
      - --sysconfdir=/var/snap/avahi-client/common/etc
      - --localstatedir=/var/snap/avahi-client/current/var
    build-packages: [pkg-config]
    install: |
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/etc
      if [ -e /snap/core/current/etc/nsswitch.conf ]; then \
          cp /snap/core/current/etc/nsswitch.conf ${SNAPCRAFT_PART_INSTALL}/etc; \
      else \
          snap download core; \
          echo "etc/nsswitch.conf" > content; \
          unsquashfs -d core -e content core_*.snap; \
          cp core/etc/nsswitch.conf ${SNAPCRAFT_PART_INSTALL}/etc; \
      fi
      sed -i -e 's/hosts:.* files dns/& mdns4/' -e 's/hosts:.* files/& mdns4_minimal [NOTFOUND=return]/' ${SNAPCRAFT_PART_INSTALL}/etc/nsswitch.conf      
      touch ${SNAPCRAFT_PART_INSTALL}/etc/mdns.allow
