name: avahi-client
adopt-info: avahi-utils
summary: Avahi sample client
description: |
    Avahi sample client

base: core24
grade: stable
confinement: strict

platforms:
  armhf:
  arm64:
  amd64:
  riscv64:

environment:
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$PATH
  LD_LIBRARY_PATH: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}

apps:
  browse:
    command: usr/bin/avahi-browse
    plugs:
      - avahi-observe

  browse-domains:
    command: usr/bin/avahi-browse-domains
    plugs:
      - avahi-observe

  publish-address:
    command: usr/bin/avahi-publish-address
    plugs:
      - avahi-control

  publish-service:
    command: usr/bin/avahi-publish-service
    plugs:
      - avahi-control

  resolve-address:
    command: usr/bin/avahi-resolve-address
    plugs:
      - avahi-observe

  resolve-host-name:
    command: usr/bin/avahi-resolve-host-name
    plugs:
      - avahi-observe

  publish:
    command: usr/bin/avahi-publish
    plugs:
      - avahi-control

  resolve:
    command: usr/bin/avahi-resolve
    plugs:
      - avahi-observe

  set-host-name:
    command: usr/bin/avahi-set-host-name
    plugs:
      - avahi-control
  ping:
    command: usr/bin/ping
    plugs:
      - avahi-control
      - network-observe

  ping6:
    command: usr/bin/ping6
    plugs:
      - avahi-control
      - network-observe

parts:
  avahi-utils:
    plugin: nil
    stage-packages:
      - avahi-utils
      - iputils-ping
      - libgdbm6t64
      - libnss-mdns
    override-build: |
      craftctl default
      version=$(awk -F '=' '$1 ~ /avahi-daemon/ {print $2;}' ../state/pull)
      craftctl set version=${version}
    stage:
      - -etc
      - -usr/sbin
      - -usr/lib/**/libavahi-core*
      - -usr/lib/**/libdaemon*
      - -usr/share
      - -var
