name: avahi-client
version: '0.0'
adopt-info: avahi-utils
summary: Avahi sample client
description: |
    Avahi sample client

base: core22
grade: stable
confinement: strict

architectures:
  - build-on: armhf
  - build-on: arm64
  - build-on: amd64
  - build-on: riscv64

environment:
  PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
  LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}

apps:
  browse:
    command: usr/bin/avahi-browse
    plugs:
      - avahi-observe

  browse-domains:
    command: usr/bin/avahi-browse-domains
    plugs:
      - avahi-observe

  publish-address:
    command: usr/bin/avahi-publish-address
    plugs:
      - avahi-control

  publish-service:
    command: usr/bin/avahi-publish-service
    plugs:
      - avahi-control

  resolve-address:
    command: usr/bin/avahi-resolve-address
    plugs:
      - avahi-observe

  resolve-host-name:
    command: usr/bin/avahi-resolve-host-name
    plugs:
      - avahi-observe

  publish:
    command: usr/bin/avahi-publish
    plugs:
      - avahi-control

  resolve:
    command: usr/bin/avahi-resolve
    plugs:
      - avahi-observe

  set-host-name:
    command: usr/bin/avahi-set-host-name
    plugs:
      - avahi-control
  ping:
    command: bin/ping
    plugs:
      - avahi-control
      - network-observe

  ping6:
    command: bin/ping6
    plugs:
      - avahi-control
      - network-observe

parts:
  avahi-utils:
    plugin: nil
    stage-packages:
      - avahi-utils
      - iputils-ping
      - libgdbm6
      - libnss-mdns
    override-build: |
      craftctl default
      version=$(awk -F '=' '$1 ~ /avahi-daemon/ {print $2;}' ../state/pull)
      craftctl set version=${version}
