name: avahi-client
version: '0.5'
summary: Avahi sample client
description: |
    Avahi sample client

grade: stable
confinement: strict

plugs:
  avahi-daemon-socket:
    interface: content
    content: avahi-daemon-socket
    default-provider: avahi:daemon-socket
    target: $SNAP_DATA/var/run/avahi-daemon

apps:
    browse:
        command: avahi-browse
        plugs:
          - avahi-observe

    browse-domains:
        command: avahi-browse-domains
        plugs:
          - avahi-observe

    publish-address:
        command: avahi-publish-address
        plugs:
          - avahi-control

    publish-service:
        command: avahi-publish-service
        plugs:
          - avahi-control

    resolve-address:
        command: avahi-resolve-address
        plugs:
          - avahi-observe

    resolve-host-name:
        command: avahi-resolve-host-name
        plugs:
          - avahi-observe

    publish:
        command: avahi-publish
        plugs:
          - avahi-control

    resolve:
        command: avahi-resolve
        plugs:
          - avahi-observe

    set-host-name:
        command: avahi-set-host-name
        plugs:
          - avahi-control
    ping:
        command: ping
        plugs:
          - avahi-control
          - network-observe

parts:
  avahi-utils:
    plugin: nil
    stage-packages: [avahi-utils,iputils-ping]

  nss-mdns:
    plugin: autotools
    source: https://github.com/lathiat/nss-mdns.git
    configflags:
      - --sysconfdir=/var/snap/avahi-client/common/etc
      - --localstatedir=/var/snap/avahi-client/current/var
    build-packages: [pkg-config]

  nsswitch:
    plugin: dump
    source: etc
