name: avahi-client
version: '0.0'
version-script: dpkg-deb -f parts/avahi-utils/ubuntu/download/avahi-utils_*.deb Version | sed 's/ubuntu.*$//g'
summary: Avahi sample client
description: |
    Avahi sample client

grade: stable
confinement: strict

plugs:
  avahi-daemon-socket:
    interface: content
    content: avahi-daemon-socket
    default-provider: avahi:daemon-socket
    target: $SNAP_DATA/var/run/avahi-daemon

passthrough:
  layout:
      /etc/nsswitch.conf:
          bind-file: $SNAP_COMMON/etc/nsswitch.conf

apps:
    browse:
        command: usr/bin/avahi-browse
        adapter: none
        environment:
          PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
          LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
        plugs:
          - avahi-observe

    browse-domains:
        command: usr/bin/avahi-browse-domains
        adapter: none
        environment:
          PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
          LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
        plugs:
          - avahi-observe

    publish-address:
        command: usr/bin/avahi-publish-address
        adapter: none
        environment:
          PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
          LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
        plugs:
          - avahi-control

    publish-service:
        command: usr/bin/avahi-publish-service
        adapter: none
        environment:
          PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
          LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
        plugs:
          - avahi-control

    resolve-address:
        command: usr/bin/avahi-resolve-address
        adapter: none
        environment:
          PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
          LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
        plugs:
          - avahi-observe

    resolve-host-name:
        command: usr/bin/avahi-resolve-host-name
        adapter: none
        environment:
          PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
          LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
        plugs:
          - avahi-observe

    publish:
        command: usr/bin/avahi-publish
        adapter: none
        environment:
          PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
          LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
        plugs:
          - avahi-control

    resolve:
        command: usr/bin/avahi-resolve
        adapter: none
        environment:
          PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
          LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
        plugs:
          - avahi-observe

    set-host-name:
        command: usr/bin/avahi-set-host-name
        adapter: none
        environment:
          PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
          LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
        plugs:
          - avahi-control
    ping:
        command: bin/ping
        adapter: none
        environment:
          PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
          LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
        plugs:
          - avahi-control
          - network-observe

    ping6:
        command: bin/ping6
        adapter: none
        environment:
          PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
          LD_LIBRARY_PATH: $SNAP_LIBRARY_PATH:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}
        plugs:
          - avahi-control
          - network-observe

parts:
  avahi-utils:
    plugin: nil
    stage-packages: [avahi-utils, iputils-ping]
    stage:
      - -var
      - -etc
      - -lib
      - -usr/bin/d*
      - -usr/bin/host
      - -usr/sbin
      - -usr/share
      - -usr/lib/avahi
      - -usr/lib/dbus-1.0
      - -usr/lib/gcc
      - -usr/lib/tmpfiles.d
    build-packages: [iputils-ping]
    override-build: |
      snapcraftctl build
      find ${SNAPCRAFT_PART_INSTALL}/usr/lib/*linux-gnu*/* ! -name "libavahi*" -exec rm -rf {} +
      find ${SNAPCRAFT_PART_INSTALL}/usr/lib/*linux-gnu*/* -name "libavahi-core*" -exec rm -f {} \;

  nss-mdns:
    plugin: autotools
    source: https://github.com/lathiat/nss-mdns.git
    configflags:
      - --sysconfdir=/var/snap/${SNAPCRAFT_PROJECT_NAME}/common/etc
      - --localstatedir=/var/snap/${SNAPCRAFT_PROJECT_NAME}/current/var
    build-packages: [pkg-config]
    override-build: |
      snapcraftctl build
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/etc
      if [ -e /snap/core/current/etc/nsswitch.conf ]; then \
          cp /snap/core/current/etc/nsswitch.conf ${SNAPCRAFT_PART_INSTALL}/etc; \
      else \
          snap download core; \
          echo "etc/nsswitch.conf" > content; \
          unsquashfs -d core -e content core_*.snap etc/nsswitch.conf; \
          cp core/etc/nsswitch.conf ${SNAPCRAFT_PART_INSTALL}/etc; \
      fi
      sed -i -e 's/hosts:.* files dns/& mdns4/' -e 's/hosts:.* files/& mdns4_minimal [NOTFOUND=return]/' ${SNAPCRAFT_PART_INSTALL}/etc/nsswitch.conf      
      touch ${SNAPCRAFT_PART_INSTALL}/etc/mdns.allow
