#!/bin/bash

exec >> $SNAP_DATA/hook.log 2>&1
echo "$(date '+%Y-%m-%d %H:%M:%S') $0: Entering hook"

set -x
mkdir -p ${SNAP_COMMON}/etc
ls ${SNAP_COMMON}/etc/

[ -e  ${SNAP_COMMON}/etc/nsswitch.conf ] && cp  ${SNAP}/etc/nsswitch.conf ${SNAP_COMMON}/etc || true
[ "$(du ${SNAP_COMMON}/etc/nsswitch.conf | cut -c -1)" = "0" ] && $SNAP/etc/nsswitch.conf > ${SNAP_COMMON}/etc/nsswitch.conf || true
